services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./backend/.env.back
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - network
    depends_on:
      - database

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - ./backend/.env.db
    volumes:
      - database:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.front
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - network
    depends_on:
      - backend
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - network


networks:
  network:
    driver: bridge

volumes:
  database:
